version: '2'
services:
    product:
        build: ./product 
        ports:
         - 5001:80
    website:
        build: ./website
        ports:
         - 5000:80
        depends_on:
         - product
